version: '3.9'

services:
  app:
    image: zys8119/anonymous-collection:latest
    container_name: anonymous-collection
    volumes:
      - ./front:/app/front
      - ./server:/app/server
    environment:
      - VITE_API_URL=http://192.168.110.76:82
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootroot
      - DB_DATABASE=api
    ports:
      - "3001:5173"
      - "82:81"
